### ISSUE TITLE
Still empty and all kinds of content holder for now

### ISSUE THREAD

**Issue by franklingu** [marcus-aurelianus/marcus-aurelianus.github.io#2]
Oooooo, mobile client cannot load the css format...so the content is not shown. It works for web client.

**Comment by marcus-aurelianus** [comment]
Still not sure why. Let me Google it...

**Comment by marcus-aurelianus** [comment]
Problem is IOS client cannot interpret the following webkit code...

Solved with following code,
change 

>     background-image: -webkit-linear-gradient(left, color-stop(#001922 20%),color-stop(#708D81 80%));
>     background-image: linear-gradient(to right, #001922 20%,#708D81 80%);

to
   
>     background-image: -webkit-gradient(linear,0% 0%, 100% 0%, from(#001922), to(#708D81));
